version: "3"
services:
  mysql:
    image: mysql:8.4.0-oraclelinux8
    container_name: aihub-mysql
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: aihub
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
  aihub:
    image: qtycc/aihub:latest
    container_name: aihub-backend
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/aihub
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456
    depends_on:
      - mysql
  nginx:
    image: nginx:latest
    container_name: aihub-nginx
    ports:
      - 80:80
    volumes:
      - ~/nginx/conf.d/aihub.conf:/etc/nginx/nginx.conf
    depends_on:
      -  aihub
volumes:
  mysql_data:
