spring:
    application:
        name: aihub
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/aihub #${SPRING_DATASOURCE_URL}
        username: root #${SPRING_DATASOURCE_USERNAME}
        password: #${SPRING_DATASOURCE_PASSWORD}
mybatis:
    type-aliases-package: com.example.aihub.pojo
    type-handlers-package: com.example.aihub.handler
    mapper-locations: classpath:mapper/*.xml
    configuration:
        mapUnderscoreToCamelCase: true

sa-token:
    # token 名称（同时也是 cookie 名称）
    token-name: satoken
    # token 有效期（单位：秒） 默认30天，-1 代表永久有效
    timeout: 2592000
    # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
    active-timeout: -1
    # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
    is-concurrent: true
    # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
    is-share: true
    # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
    token-style: uuid
    # 是否输出操作日志
    is-log: true

ai:
    deepseek:
        api_key: 2264080d-8e47-4b0c-9fe8-1849c696bb5e
    doubao:
        api_key: f19d6d18-8658-4770-80e5-f9d92622d1e1