spring:
    application:
        name: aihub
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: ${SPRING_DATASOURCE_URL}
        username: ${SPRING_DATASOURCE_USERNAME}
        password: ${SPRING_DATASOURCE_PASSWORD}
mybatis:
    type-aliases-package: com.example.aihub.pojo
    mapper-locations: classpath:mapper/*.xml
    configuration:
        mapUnderscoreToCamelCase: true

deepseek:
    api_key: 2264080d-8e47-4b0c-9fe8-1849c696bb5e